plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

ext {
    springBootVersion = '3.5.9'
}
dependencies {
    implementation platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
    implementation("org.projectlombok:lombok:1.18.42")
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springdoc:springdoc-openapi-starter-common:2.8.6'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}